import type { Metadata } from 'next';
import '../styles/global.scss';
import 'katex/dist/katex.min.css'; // Apply KaTeX style
import Header from './_components/Header';
import Footer from './_components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Header />
        <hr />
        <hr />
        <section className="max-w-[1200px] mx-auto">
          {children}
          <Footer />
        </section>
      </body>
    </html>
  );
}
