import type { Metadata } from 'next';
import '../styles/global.scss';
import 'katex/dist/katex.min.css'; // Apply KaTeX style
import Header from './_components/common/Header';
import Footer from './_components/common/Footer';
import GoToTopButton from './_components/common/GoToTopButton';
import QueryProvider from './_providers/QueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className="min-h-[100vh]">
        <QueryProvider>
          <Header />
          <hr />
          <hr />
          <section className="max-w-[1200px] px-4 mx-auto mb-auto h-full">
            {children}
          </section>
          <GoToTopButton />
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
